

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(07f00050-ee45-45a5-bcee-97f1c569b200)'
    appType: 'webAppLinux'
    WebAppName: 'test-app-for-pipeline-alev'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'PHP|7.4'